services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${DB_SA_PASSWORD}
    ports:
      - "1433:1433"
    networks:
      - net
    volumes:
      - dbdata:/var/opt/mssql
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/1433"]
      interval: 10s
      timeout: 5s
      retries: 10

  db-setup:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      db:
        condition: service_healthy
    entrypoint: >
      bash -c "
        /opt/mssql-tools/bin/sqlcmd -S db -U sa -P ${DB_SA_PASSWORD} -i /scripts/init.sql
      "
    volumes:
      - ./db-init:/scripts
    networks:
      - net

  api:
    build:
      context: ./API
      dockerfile: Dockerfile
    container_name: api
    depends_on:
      - db-setup
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DB_CONNECTION_STRING: ${API_DB_CONNECTION_STRING}
    ports:
      - "5000:80"
    networks:
      - net

  client:
    build:
      context: ./Client
      dockerfile: Dockerfile
    container_name: client
    depends_on:
      - api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      API_BASE_URL: http://api
    ports:
      - "5001:80"
    networks:
      - net

networks:
  net:

volumes:
  dbdata:
