IF DB_ID('WEATHER_DB') IS NULL
BEGIN
    CREATE DATABASE WEATHER_DB;
END;
GO

USE WEATHER_DB;
GO

IF NOT EXISTS (
    SELECT
        *
    FROM
        SYSOBJECTS
    WHERE
        NAME = 'WEATHERFORECASTS'
        AND XTYPE = 'U'
)
BEGIN
    CREATE TABLE WEATHERFORECASTS (
        ID INT PRIMARY KEY IDENTITY (1, 1),
        DATE DATE NOT NULL,
        TEMPERATUREC INT NOT NULL,
        SUMMARY NVARCHAR(100) NULL
    );
END;
GO
